import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const envPath = resolve(repoRoot, ".env.local");

function npmCommand() {
  return process.platform === "win32" ? "npm.cmd" : "npm";
}

function runNpm(args, options = {}) {
  const npmCli = process.env.npm_execpath;
  return npmCli
    ? run(process.execPath, [npmCli, ...args], options)
    : run(npmCommand(), args, options);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: "pipe",
    ...options,
  });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    const detail = `${result.stdout ?? ""}\n${result.stderr ?? ""}`.trim();
    throw new Error(detail || `${command} ${args.join(" ")} failed.`);
  }
  return `${result.stdout ?? ""}\n${result.stderr ?? ""}`;
}

function readEnvFile(path) {
  if (!existsSync(path)) {
    return {};
  }

  return Object.fromEntries(
    readFileSync(path, "utf8")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#"))
      .map((line) => {
        const index = line.indexOf("=");
        if (index < 1) {
          return [];
        }
        return [line.slice(0, index), line.slice(index + 1)];
      })
      .filter((entry) => entry.length === 2),
  );
}

export function readSupabaseStatusEnv() {
  const output = runNpm(["exec", "--", "supabase", "status", "-o", "env"]);
  return Object.fromEntries(
    output
      .split(/\r?\n/)
      .map((line) => line.trim())
      .map((line) => {
        const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
        if (!match) {
          return [];
        }
        let value = match[2].trim();
        if (value.startsWith('"') && value.endsWith('"')) {
          value = value.slice(1, -1);
        }
        return [match[1], value];
      })
      .filter((entry) => entry.length === 2),
  );
}

export function dockerAvailable() {
  const dockerCheck = spawnSync("docker", ["info"], {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: "pipe",
  });
  return dockerCheck.status === 0;
}

function writeLocalEnv({ apiUrl, anonKey, serviceRoleKey }) {
  const existingEnv = readEnvFile(envPath);
  if (
    existingEnv.NEXT_PUBLIC_SUPABASE_URL &&
    !/^http:\/\/(?:127\.0\.0\.1|localhost):54321\/?$/.test(
      existingEnv.NEXT_PUBLIC_SUPABASE_URL,
    )
  ) {
    throw new Error(
      ".env.local 已存在且指向非本地 Supabase；请先手动检查后再运行 bootstrap。",
    );
  }

  const nextEnv = {
    ...existingEnv,
    NEXT_PUBLIC_SUPABASE_URL: apiUrl,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: anonKey,
    SUPABASE_SERVICE_ROLE_KEY: serviceRoleKey,
    OPENAI_API_KEY: existingEnv.OPENAI_API_KEY || "local-mock-only",
    OPENAI_BASE_URL: existingEnv.OPENAI_BASE_URL || "http://127.0.0.1:4010/v1",
    OPENAI_VISION_MODEL:
      existingEnv.OPENAI_VISION_MODEL || "kids-museum-local-mock",
    OPENAI_TRANSCRIPTION_MODEL:
      existingEnv.OPENAI_TRANSCRIPTION_MODEL ||
      "kids-museum-local-transcribe",
  };

  const content = [
    "# Generated by tools/bootstrap-local.mjs. This file is ignored by Git.",
    ...Object.entries(nextEnv).map(([key, value]) => `${key}=${value}`),
    "",
  ].join("\n");
  writeFileSync(envPath, content, "utf8");
}

export function ensureLocalSupabaseReady({ skipOnMissingDocker = false } = {}) {
  if (!dockerAvailable()) {
    if (skipOnMissingDocker) {
      return {
        skipped: true,
        reason:
          "Docker Desktop 未安装或未启动；已跳过需要本地 Supabase stack 的验证。",
      };
    }
    throw new Error(
      "Docker Desktop is required and must be running with Linux containers.",
    );
  }

  runNpm(["exec", "--", "supabase", "start"]);
  const status = readSupabaseStatusEnv();
  const apiUrl = status.API_URL?.trim();
  const anonKey = (status.ANON_KEY || status.PUBLISHABLE_KEY || "").trim();
  const serviceRoleKey = (status.SERVICE_ROLE_KEY || status.SECRET_KEY || "").trim();
  if (!apiUrl || !anonKey || !serviceRoleKey) {
    throw new Error("无法从本地 Supabase 读取 API_URL / 本地密钥。");
  }

  writeLocalEnv({ apiUrl, anonKey, serviceRoleKey });
  run("node", ["tools/setup-local-resources.mjs"], {
    env: {
      ...process.env,
      LOCAL_SUPABASE_URL: apiUrl,
      LOCAL_SUPABASE_SERVICE_ROLE_KEY: serviceRoleKey,
    },
  });

  return {
    skipped: false,
    apiUrl,
    anonKey,
    serviceRoleKey,
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const result = ensureLocalSupabaseReady();
  if (result.skipped) {
    console.log(result.reason);
  } else {
    console.log("Local Supabase is ready.");
  }
}
